### PR TITLE
Added parameters + API endpoints for random words

### PR DESCRIPTION
**Pull request by LilithL**
I needed the random word feature from wordnik for another project (also in case it might interest you).
So here I'm making a pull request since I don't own the crate on crates.io

Thanks in advance

### CODE REVIEW

**Comment by archer884** [comment]
Hey, @LilithL, I really appreciate you taking the time to offer some code. That said, I have a couple issues here.

First, I don't really like the idea of replacing the `definitions(word)` call with one that usually looks like `definitions(word, None)`; it feels suboptimal somehow. In my own mind, I'm thinking the thing to do would be to offer a simple method for just getting the definitions with the default settings and a second method for passing in a parameters object.

Second, while the macros are pretty cool, the way they seem to implement the conversion from a struct into a set of key/value pairs ("foo=bar&baz=basil") looks to be about equivalent to the following:

```rust
let buf = String::new();
let buf = format!("{}&{}={}", buf, key, value);
let buf = format!("{}&{}={}", buf, key1, value1);
let buf = format!("{}&{}={}", buf, key2, value2);
// etc., etc.
```

This means N allocations, where N is the number of fields on a given params object, which is less than ideal. I realize that just naively writing keys and values to a string is going to result in the computer doing almost the same amount of work, but this looks like it's pretty much the worst case scenario, a la C#. =)

Finally, I'm not tooootally convinced that the params structs have the right fields in them. For instance, `useCanonical` is boolean, but `includeRelated` is a string. That's weird. Additionally, we've got these params structs but haven't provided the user with any idea what goes in them--with `includedRelated` being a good example. If that's not boolean, what are the correct values? And of course then there are items like `sourceDictionaries` and `partOfSpeech`, which even my mom would have trouble filling in from memory--and we've got those represented as a single string, even though the API accepts multiple values for both of these. The user can just put in "ahd-5,webster" as the value, of course, but at that point I wonder if this is providing much value over just accepting a string of additional parameters, like `definitions_raw("gerbil", "sourceDictionaries=ahd-5,cmu,wiktionary")`.

These are all the things I wound up thinking about when I was trying to decide what api to present in the first place, and I never did come up with good answers, which is why the api I wrote just presents the default options to the server. I figured, "Someday, I'll think of a better plan." Obviously, I haven't yet.

I dunno. What do you think? I sketched out some thoughts in here, but it's far from complete, and there's a LOT of code in there. https://github.com/archer884/wordnik/tree/feature/queries-with-args/src

**Comment by LilithL** [comment]
Tbh i find those draft quite neat, moreover it could allow us an easier way of documenting the API endpoints and its parameters to allow user to use what they need without checking the wordnik API docs everytime.

I thought maybe it could be interesting, for comment purpose to also separate args in sub-files. Those would still be in the module in **src/args** ofc, but just to make things more easy to comment, or would this seem too much ?
Sub-files, for example, could be for the words and word API endpoints and also a third file containing the enums like you did with **PartOfSpeech** ?

I'll work on it later if you think it could be interesting to see/if you need more explainations about what i'm thinking

**Comment by LilithL** [comment]
Hi, I've finally changed things as we talked about (yeah, it's been 7 months sorry x) ).
I took your draft and replaced the macro system with it so now it's easier to manage args and parse them into an URI with the help of an iterator.
I also made two separate functions for api calls with and without args as you suggested. (Only for definitions, randomWords and randomWord API calls tho)

let me know if some things would be better/need some changes ^^

**Comment by archer884** [comment]
Hey, I saw this, I just haven't had a chance to look. Will get back to you. (Told Siri to remind me.)

**Comment by archer884** [comment]
Sent you a pull request with some modifications. Would you review that when you get the chance?

**Comment by archer884** [comment]
Thanks again, @LilithL 

Edit: released new version on crates.io

**Pull request merged**
